#!/usr/bin/env ruby

$checks_failed = 0

def check(name)
  STDOUT.write(" * #{name}...")
  STDOUT.flush
  result = yield
  if result == true
    puts(" ok!")
  else
    puts(" error: #{result}")
    $checks_failed += 1
  end
end

def sh(*command)
  puts command.join(' ')
  if !system(*command)
    abort "*** Command failed"
  end
end

def main
  check("Checking for SSH key") do
    if File.exist?("/secure_key.pub")
      true
    else
      "please save your SSH public key as /secure_key.pub"
    end
  end
  abort if $checks_failed > 0

  puts
  puts "--- Setting up system ---"
  sh "cat /secure_key.pub > /root/.ssh/authorized_keys"
  sh "rm -f /secure_key.pub"
  sh "rm -f /usr/sbin/setup-system"
end

main
