#!/bin/bash
# Forwards the Nginx error.log to the Docker logs.
set -e
if [[ ! -e /var/log/nginx/error.log ]]; then
	touch /var/log/nginx/error.log
fi
echo "*** Running tail -F /var/log/nginx/error.log"
exec tail -F /var/log/nginx/error.log
